/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.Conexao;
import controler.ControllerMarca;
import controler.ControllerNotebook;
import dao.DaoNotebookImp;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Notebook;
/**
 *
 * @author soare
 */
public class CadastroNot extends javax.swing.JInternalFrame {
    List<Notebook> notebooks;
    List<String> marcas;
    ControllerNotebook controlnote = new ControllerNotebook();
    ControllerMarca controlmarca=  new ControllerMarca();
    int indece;
    public CadastroNot() {
        initComponents();
        idNot.setEnabled(false);
        
        indece = 0;
        notebooks = controlnote.recarregaLista();
        marcas=controlmarca.carregaCombo();
        
        while(!marcas.isEmpty()){
            cbxMarca.addItem(marcas.get(0));
            marcas.remove(0);
        }
        if(notebooks.isEmpty()){
            JOptionPane.showMessageDialog(this,"Não existem dados cadastrado!");
        }
        else{
             mostrarDados();
             preencherTabela();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        idNot = new javax.swing.JTextField();
        modeloNot = new javax.swing.JTextField();
        cbxMarca = new javax.swing.JComboBox<>();
        serie = new javax.swing.JFormattedTextField();
        lbTituloNot = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotebooks = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Notebooks");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(true);

        jLabel1.setText("ID:");

        jLabel2.setText("Modelo");

        jLabel3.setText("Marca");

        jLabel4.setText("Serie:");

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnProximo.setText("Proximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        jButton4.setText("Ultimo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        idNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNotActionPerformed(evt);
            }
        });

        cbxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Selecionar--" }));
        cbxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaActionPerformed(evt);
            }
        });

        try {
            serie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTituloNot.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbTituloNot.setForeground(new java.awt.Color(0, 153, 153));
        lbTituloNot.setText("Cadastro Notebooks ");

        tblNotebooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "MODELO", "MARCA", "SERIE"
            }
        ));
        tblNotebooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNotebooksMouseClicked(evt);
            }
        });
        tblNotebooks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblNotebooksKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblNotebooks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(modeloNot, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serie, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, 187, Short.MAX_VALUE)
                                    .addComponent(idNot)))
                            .addComponent(lbTituloNot)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnPrimeiro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAnterior)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnProximo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnAlterar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCadastrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNovo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTituloNot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idNot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(modeloNot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnterior)
                            .addComponent(btnProximo)
                            .addComponent(jButton4)
                            .addComponent(btnPrimeiro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAlterar)
                                .addComponent(btnExcluir)
                                .addComponent(btnNovo)))
                        .addGap(75, 75, 75))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNotActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indece--;
        if(indece<0){
           indece--;
           JOptionPane.showMessageDialog(null,"Você já está no primeiro registro!");
        }
        
        mostrarDados();
       
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Notebook n = new Notebook();
        n.setId(Integer.parseInt(idNot.getText()));
        n.setModelo(modeloNot.getText());
        n.setMarca(controlmarca.getIdByMarca((String)cbxMarca.getSelectedItem()));
        n.setSerie(serie.getText());
        
        controlnote.alterarNotebook(n);
        notebooks = controlnote.recarregaLista();
        indece=notebooks.size()-1;
        mostrarDados();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
         idNot.setText("");
         modeloNot.setText("");
         cbxMarca.setSelectedItem("---Selecionar--");
         serie.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void cbxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMarcaActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        indece= 0;
        mostrarDados();
        btnAnterior.setEnabled(false);
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
       btnAnterior.setEnabled(true);
        indece++;
        if(indece>notebooks.size()-1){
           indece--;
           JOptionPane.showMessageDialog(null,"Você já está no ultimo registro!");
        }
        mostrarDados();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        btnAnterior.setEnabled(true);
        indece=notebooks.size()-1;
        mostrarDados();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Notebook n = new Notebook();
        
        n.setModelo(modeloNot.getText());
        n.setMarca(controlmarca.getIdByMarca((String)cbxMarca.getSelectedItem()));
        n.setSerie(serie.getText());
        
        controlnote.salvarNotebook(n);
        notebooks = controlnote.recarregaLista();
        indece=notebooks.size()-1;
        mostrarDados();
        preencherTabela();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       
        int excluir = Integer.parseInt(idNot.getText());
        controlnote.excluirNotebook(excluir);
          notebooks = controlnote.recarregaLista();
          indece=notebooks.size()-1;
          mostrarDados();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblNotebooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNotebooksMouseClicked
      preencherFormDaTabela();
    }//GEN-LAST:event_tblNotebooksMouseClicked

    private void tblNotebooksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblNotebooksKeyReleased
       if(evt.getKeyCode()==38 || evt.getKeyCode()==40){
           preencherFormDaTabela();
       }
    }//GEN-LAST:event_tblNotebooksKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JTextField idNot;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTituloNot;
    private javax.swing.JTextField modeloNot;
    private javax.swing.JFormattedTextField serie;
    private javax.swing.JTable tblNotebooks;
    // End of variables declaration//GEN-END:variables
    public void mostrarDados(){
            idNot.setText(""+notebooks.get(indece).getId());
            modeloNot.setText(notebooks.get(indece).getModelo());
            cbxMarca.setSelectedItem(controlmarca.getMarcaById(notebooks.get(indece).getMarca()));
            serie.setText(notebooks.get(indece).getSerie());
    }
    public void excluirDados(int id){
            
            DaoNotebookImp d=new DaoNotebookImp();
            int x= Integer.parseInt(idNot.getText());
            
    }
   public void preencherTabela(){
       notebooks=controlnote.recarregaLista();
       
       tblNotebooks.getColumnModel().getColumn(0).setPreferredWidth(5);
       tblNotebooks.getColumnModel().getColumn(1).setPreferredWidth(40);
       tblNotebooks.getColumnModel().getColumn(2).setPreferredWidth(40);
       tblNotebooks.getColumnModel().getColumn(3).setPreferredWidth(15);
       
       DefaultTableModel modelo = (DefaultTableModel)tblNotebooks.getModel();
       modelo.setNumRows(0);
       for(int i = 0; i< notebooks.size(); i++){
           modelo.addRow(new Object[]{
               notebooks.get(i).getId(),
               notebooks.get(i).getModelo(),
               notebooks.get(i).getMarca(),
               notebooks.get(i).getSerie()
           });
       }
   }
   public void preencherFormDaTabela(){
       int descobrelinha = tblNotebooks.getSelectedRow();
       idNot.setText(tblNotebooks.getValueAt(descobrelinha,0).toString());
       modeloNot.setText(tblNotebooks.getValueAt(descobrelinha,1).toString());
       cbxMarca.setSelectedItem(tblNotebooks.getValueAt(descobrelinha,2).toString());
       serie.setText(tblNotebooks.getValueAt(descobrelinha,3).toString());
        
   }
}
